# Generated by Django 4.1.5 on 2023-01-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_user_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('N', 'Prefer not to tell')], null=True),
        ),
    ]
