# Generated by Django 4.1.5 on 2023-01-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_subject_user_subject_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='post_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
