# Generated by Django 4.1.5 on 2023-01-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_user_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='privacy',
        ),
    ]
